=== antoine-tran/callisto/callisto/tasks/ace2004/resource/maia.dtd
<!--

A DTD for the Meta-Annotation Infrastructure for ATLAS [MAIA].
MAIA provides a type definition language part of which grammar
is recorded in this DTD.

NOTE: This DTD is a preliminary version and is bound to change.

Current maintainer: Chris Laprun [ chris.laprun@nist.gov ]

$Id: maia.dtd,v 1.1 2004/12/17 23:36:43 red Exp $

-->

<!-- Registered MIME Types:  copied from 'common.ent' -->
<!-- see http://www.isi.edu/in-notes/iana/assignments/media-types/media-types

- application
- audio
- image
- message
- model
- multipart
- text
- video

-->
<!ENTITY % MCSupported "application | audio | image | text | video">
<!ENTITY % MCOthers "message | model | multipart">
<!ENTITY % MIMEClasses "%MCSupported;">

<!ENTITY % MIMETypes "NMTOKEN">

<!-- Registered Parameter datatypes -->
<!ENTITY % DataTypes "boolean | float | int | string | other">

<!-- End of common.xml -->

<!ENTITY % stdAtt "
     name NMTOKEN #IMPLIED
     ref NMTOKEN #IMPLIED
     role NMTOKEN #IMPLIED
     hasIndefiniteCardinality (true) #IMPLIED">

<!ENTITY % definedAsAtt "
  ref NMTOKEN #REQUIRED
  byChildrenWithRole NMTOKEN #REQUIRED
  isOrderMeaningful (true) #IMPLIED">

<!ENTITY % TypeDefinitionsCM "(AnalysisType | AnnotationType | ContentType |
  ChildrenType | RegionType | FeatureType | AnchorType | ParameterType |
  SignalType | SignalGroupType | CorpusType)">

<!ENTITY % FeatureCM "(FeatureType*|ParameterType*)">

<!ENTITY % ChildrenCM "(AnnotationType?)">

<!ENTITY % RegionDefinedAsCM "EMPTY">
<!ENTITY % ContentDefinedAsCM "EMPTY">

<!ELEMENT Scheme (Import*, TypeDefinitions, ConstraintDefinitions?)>
<!ATTLIST Scheme
  name NMTOKEN #REQUIRED
  MAIAVersion CDATA #FIXED "0.4"
>

<!ELEMENT Import EMPTY>
<!ATTLIST Import
  location CDATA #REQUIRED
  withName NMTOKEN #IMPLIED
>

<!ELEMENT TypeDefinitions (%TypeDefinitionsCM;)*>

<!ELEMENT ConstraintDefinitions EMPTY>

<!ELEMENT CorpusType ((SignalType | SignalGroupType)+, AnchorType+, RegionType+, AnalysisType+)>
<!ATTLIST CorpusType
  %stdAtt;
>

<!ELEMENT AnalysisType (AnnotationType*)>
<!ATTLIST AnalysisType
  %stdAtt;
>

<!ELEMENT AnnotationType (RegionType?,ContentType?,ChildrenType*,RegionDefinedAs?,ContentDefinedAs?)>
<!ATTLIST AnnotationType
  %stdAtt;
>

<!ELEMENT AnchorType (SignalType?,ParameterType*)>
<!ATTLIST AnchorType
  %stdAtt;
>

<!ELEMENT RegionType (AnchorType*,RegionType*,AnnotationType*)>
<!ATTLIST RegionType
  %stdAtt;
>

<!ELEMENT ContentType %FeatureCM;>
<!ATTLIST ContentType
  %stdAtt;
>

<!ELEMENT ParameterType EMPTY>
<!ATTLIST ParameterType
  %stdAtt;
>

<!ELEMENT SignalType EMPTY>
<!ATTLIST SignalType
  %stdAtt;
  mimeClass (%MIMEClasses;) #IMPLIED
>

<!ELEMENT SignalGroupType (SignalType | SignalGroupType)*>
<!ATTLIST SignalGroupType
  %stdAtt;
>

<!ELEMENT FeatureType %FeatureCM;>
<!ATTLIST FeatureType
  %stdAtt;
>

<!ELEMENT ChildrenType %ChildrenCM;>
<!ATTLIST ChildrenType
  %stdAtt;
>

<!ELEMENT RegionDefinedAs %RegionDefinedAsCM;>
<!ATTLIST RegionDefinedAs
  %definedAsAtt;
>

<!ELEMENT ContentDefinedAs %ContentDefinedAsCM;>
<!ATTLIST ContentDefinedAs
  %definedAsAtt;
>

=== antoine-tran/callisto/callisto/tasks/spatialml/resource/spatialml.maia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Scheme SYSTEM "maia.dtd" >

<!-- The Scheme name here is the same as the task name. which needn't
     correspond exactly to the class name, it need only be unambiguous
     amongst Callisto Tasks.
  -->

<Scheme name="org.mitre.spatialml">
  <TypeDefinitions>
    <SignalType name="text" mimeClass="text" />
    
    <ParameterType name="char" />
    <ParameterType name="string" />

    <AnchorType name="text-point">
      <SignalType ref="text" role="text"/>
      <ParameterType ref="char" role="char"/>
    </AnchorType>

    <RegionType name="text-extent">
      <AnchorType ref="text-point" role="start"/>
      <AnchorType ref="text-point" role="end"/>
    </RegionType>

	<RegionType name="rlink-subordinates">
		<AnnotationType ref="PLACE" role="source" />
		<AnnotationType ref="PLACE" role="target" />
<!--		<AnnotationType ref="iPLACE" role="iSource" />-->
<!--		<AnnotationType ref="iPLACE" role="iTarget" />-->
		<AnnotationType ref="SIGNAL" hasIndefiniteCardinality="true" />
	</RegionType>

	<RegionType name="link-subordinates">
		<AnnotationType ref="PLACE" role="source" />
		<AnnotationType ref="PLACE" role="target" />
		<AnnotationType ref="RLINK" role="sourceRlink" />
		<AnnotationType ref="RLINK" role="targetRlink" />
		<AnnotationType ref="SIGNAL" hasIndefiniteCardinality="true" />
<!--		<AnnotationType ref="PLACE" hasIndefiniteCardinality="true" />-->
	</RegionType>

    <ContentType name="null-content"></ContentType>
    
    <ContentType name="place-content">
    	<ParameterType ref="string" role="id" />
    	<ParameterType ref="string" role="gazref" />
    	<ParameterType ref="string" role="comment" />
    	<ParameterType ref="string" role="type" />
    	<ParameterType ref="string" role="mod" />
    	<ParameterType ref="string" role="continent" />
    	<ParameterType ref="string" role="country" />
    	<ParameterType ref="string" role="county" />
    	<ParameterType ref="string" role="state" />
    	<ParameterType ref="string" role="latLong" />
    	<ParameterType ref="string" role="nonLocUse" />
    	<ParameterType ref="string" role="predicative" />
    	<ParameterType ref="string" role="description" />
		<ParameterType ref="string" role="form" />
    	<ParameterType ref="string" role="CTV" />
    </ContentType>

	<AnnotationType name="PLACE">
		<RegionType ref="text-extent" role="text-extent" />
		<ContentType ref="place-content" role="content" />
	</AnnotationType>

<!--	<AnnotationType name="iPLACE">-->
<!--		<RegionType ref="text-extent" role="text-extent" />-->
<!--		<ContentType ref="place-content" role="content" />-->
<!--	</AnnotationType>-->
		

	<ContentType name="rlink-content">
    	<ParameterType ref="string" role="id" />
    	<ParameterType ref="string" role="comment" />
    	<ParameterType ref="string" role="frame" />
    	<ParameterType ref="string" role="direction" />
    	<ParameterType ref="string" role="distance" />
	</ContentType>
	
	<AnnotationType name="RLINK">
		<RegionType ref="rlink-subordinates" role="subordinates" />
		<ContentType ref="rlink-content" role="content" />
	</AnnotationType>

	<AnnotationType name="rlink-extent">
		<RegionType ref="text-extent" role="text-extent" />
		<ContentType ref="null-content" role="content" />
	</AnnotationType>
	
	<ContentType name="signal-content">
    	<ParameterType ref="string" role="id" />
    	<ParameterType ref="string" role="comment" />
    	<ParameterType ref="string" role="signalType" />
	</ContentType>
	
	<AnnotationType name="SIGNAL">
		<RegionType ref="text-extent" role="text-extent" />
		<ContentType ref="signal-content" role="content" />
	</AnnotationType>

	<AnnotationType name="link-extent">
		<RegionType ref="text-extent" role="text-extent" />
		<ContentType ref="null-content" role="content" />
	</AnnotationType>

	<ContentType name="link-content">
    	<ParameterType ref="string" role="id" />
    	<ParameterType ref="string" role="comment" />
    	<ParameterType ref="string" role="linkType" />
	</ContentType>

	<AnnotationType name="LINK">
		<RegionType ref="link-subordinates" role="subordinates" />
		<ContentType ref="link-content" role="content" />
	</AnnotationType>

    <AnalysisType name="place-set">
    	<AnnotationType ref="PLACE" hasIndefiniteCardinality="true" />
    </AnalysisType>
    
    <AnalysisType name="rlink-set">
    	<AnnotationType ref="RLINK" hasIndefiniteCardinality="true" />
    </AnalysisType>

    <AnalysisType name="rlink-extent-set">
    	<AnnotationType ref="rlink-extent" hasIndefiniteCardinality="true" />
    </AnalysisType>
    
    <AnalysisType name="signal-set">
    	<AnnotationType ref="SIGNAL" hasIndefiniteCardinality="true" />
    </AnalysisType>
    
    <AnalysisType name="link-extent-set">
    	<AnnotationType ref="link-extent" hasIndefiniteCardinality="true" />
    </AnalysisType>

    <AnalysisType name="link-set">
    	<AnnotationType ref="LINK" hasIndefiniteCardinality="true" />
    </AnalysisType>
    
    
    
    <CorpusType name="spatialml">
    	<SignalType ref="text" hasIndefiniteCardinality="true" />
    	<AnchorType ref="text-point" hasIndefiniteCardinality="true" />
    	
    	<RegionType ref="text-extent" hasIndefiniteCardinality="true" />
    	<RegionType ref="link-subordinates" hasIndefiniteCardinality="true" />
    	<RegionType ref="rlink-subordinates" hasIndefiniteCardinality="true" />
    	
    	<AnalysisType ref="place-set" hasIndefiniteCardinality="true" />
    	<AnalysisType ref="rlink-set" hasIndefiniteCardinality="true" />
    	<AnalysisType ref="rlink-extent-set" hasIndefiniteCardinality="true" />
    	<AnalysisType ref="signal-set" hasIndefiniteCardinality="true" />
    	<AnalysisType ref="link-set" hasIndefiniteCardinality="true" />
    	<AnalysisType ref="link-extent-set" hasIndefiniteCardinality="true" />
    	
    </CorpusType>
    
  </TypeDefinitions>
</Scheme>

=== antoine-tran/callisto/callisto/tasks/timex2/resource/timex2.maia.xml
<?xml version="1.0"?>
<!DOCTYPE Scheme SYSTEM 'maia.dtd'>

<!-- The Scheme name here is the same as the task name. which needn't
     correspond exactly to the class name, it need only be unambiguous
     amongst Callisto Tasks.
  -->
<Scheme name="org.mitre.timex2">
  <TypeDefinitions>
    <SignalType name="text" mimeClass="text"/>

    <ParameterType name="char"/>    
    <ParameterType name="string"/>

    <AnchorType name="text-point">
      <SignalType ref="text" role="text"/>
      <ParameterType ref="char" role="char"/>
    </AnchorType>

    <RegionType name="text-extent">
      <AnchorType ref="text-point" role="start"/>
      <AnchorType ref="text-point" role="end"/>
    </RegionType>


    <ContentType name="timex-content">
      <ParameterType ref='string' role='val'/>
      <ParameterType ref='string' role='mod'/>
      <ParameterType ref='string' role='set'/> 
      <ParameterType ref='string' role='non-specific'/>
      <ParameterType ref='string' role='anchor-val'/>
      <ParameterType ref='string' role='anchor-dir'/>
      <ParameterType ref='string' role='comment'/> 
      <ParameterType ref='string' role='no-val'/>
    </ContentType>

    <AnnotationType name="TIMEX2">
      <RegionType ref="text-extent" role="text-extent"/>
      <ContentType ref="timex-content" role="content"/>
    </AnnotationType>

    <AnalysisType name="timex-set">
      <AnnotationType ref="TIMEX2" hasIndefiniteCardinality="true"/>
    </AnalysisType>

    <CorpusType name="timex2">
      <SignalType ref="text" hasIndefiniteCardinality="true"/>
      <AnchorType ref="text-point" hasIndefiniteCardinality="true"/>
      <RegionType ref="text-extent" hasIndefiniteCardinality="true"/>
      <AnalysisType ref="timex-set" role="timex-set" />      
    </CorpusType>

  </TypeDefinitions>
</Scheme>

=== antoine-tran/callisto/callisto/src/org/mitre/jawb/resources/maia/GPEPhraseTagging.maia.xml
<?xml version="1.0"?>
<!DOCTYPE Scheme SYSTEM 'maia.dtd'>

<Scheme name='simple-phrase-tagging'>
  <TypeDefinitions>
    <SignalType name='text' mimeClass='text'/>

    <AnalysisType name='all-tags'>
      <AnnotationType ref='phrase-tag' hasIndefiniteCardinality='true'/>
    </AnalysisType>

    <AnchorType name='text-point'>
      <SignalType ref='text' role='text'/>
      <ParameterType ref='char' role='char'/>
    </AnchorType>

    <RegionType name='text-extent'>
      <AnchorType ref='text-point' role='start'/>
      <AnchorType ref='text-point' role='end'/>
    </RegionType>

    <AnnotationType name='phrase-tag'>
      <RegionType ref='text-extent' role='text-extent'/>
	<ContentType ref='two-parameter-content' role='attr-val-content'/>
    </AnnotationType>

    <ContentType name='two-parameter-content'>
	<ParameterType ref='string' role='type'/>
    </ContentType>

    <ParameterType name='char'/>    
    <ParameterType name='string'/>

    <CorpusType name='simple'>
      <SignalType ref='text' hasIndefiniteCardinality='true'/>
      <AnchorType ref='text-point' hasIndefiniteCardinality='true'/>
      <RegionType ref='text-extent' hasIndefiniteCardinality='true'/>
      <AnalysisType ref='all-tags' role='all-tags'/>
    </CorpusType>
  </TypeDefinitions>
</Scheme>

=== antoine-tran/callisto/callisto/tasks/muc/resource/MUC.other.maia.xml
<?xml version="1.0"?>
<!DOCTYPE Scheme SYSTEM 'maia.dtd'>

<!-- The Scheme name here is the same as the task name. which needn't
     correspond exactly to the class name, it need only be unambiguous
     amongst Callisto Tasks.
  -->
<Scheme name="org.mitre.muc.other">
  <TypeDefinitions>
    <SignalType name="text" mimeClass="text"/>

    <ParameterType name="char"/>    
    <ParameterType name="string"/>

    <AnchorType name="text-point">
      <SignalType ref="text" role="text"/>
      <ParameterType ref="char" role="char"/>
    </AnchorType>

    <RegionType name="text-extent">
      <AnchorType ref="text-point" role="start"/>
      <AnchorType ref="text-point" role="end"/>
    </RegionType>


    <!-- Contents -->
    <ContentType name="type-content">
      <ParameterType ref="string" role="type"/>
    </ContentType>

    <ContentType name="null-content"></ContentType>

    <!-- Annotations -->
    <AnnotationType name="ENAMEX">
      <RegionType ref="text-extent" role="text-extent"/>
      <ContentType ref="type-content" role="content"/>
    </AnnotationType>

    <AnnotationType name="TIMEX">
      <RegionType ref="text-extent" role="text-extent"/>
      <ContentType ref="type-content" role="content"/>
    </AnnotationType>

    <AnnotationType name="NUMEX">
      <RegionType ref="text-extent" role="text-extent"/>
      <ContentType ref="type-content" role="content"/>
    </AnnotationType>

    <AnnotationType name="OTHER">
      <RegionType ref="text-extent" role="text-extent"/>
      <ContentType ref="null-content" role="content"/>
    </AnnotationType>


    <AnalysisType name="enamex-set">
      <AnnotationType ref="ENAMEX" hasIndefiniteCardinality="true"/>
    </AnalysisType>

    <AnalysisType name="timex-set">
      <AnnotationType ref="TIMEX" hasIndefiniteCardinality="true"/>
    </AnalysisType>

    <AnalysisType name="numex-set">
      <AnnotationType ref="NUMEX" hasIndefiniteCardinality="true"/>
    </AnalysisType>

    <AnalysisType name="other-set">
      <AnnotationType ref="OTHER" hasIndefiniteCardinality="true"/>
    </AnalysisType>

    <CorpusType name="muc">
      <SignalType ref="text" hasIndefiniteCardinality="true"/>
      <AnchorType ref="text-point" hasIndefiniteCardinality="true"/>
      <RegionType ref="text-extent" hasIndefiniteCardinality="true"/>

      <AnalysisType ref="enamex-set" role="enamex-set" />
      <AnalysisType ref="timex-set" role="timex-set" />      
      <AnalysisType ref="numex-set" role="numex-set" />
      <AnalysisType ref="other-set" role="other-set" />
    </CorpusType>

  </TypeDefinitions>
</Scheme>

=== antoine-tran/callisto/callisto/tasks/sample/resource/Sample.maia.xml
<?xml version="1.0"?>
<!DOCTYPE Scheme SYSTEM 'maia.dtd'>

<!-- The Scheme name here is the same as the task name. which needn't
     correspond exactly to the class name, it need only be unambiguous
     amongst Callisto Tasks.
  -->
<Scheme name='org.mitre.sample'>
  <TypeDefinitions>
    <SignalType name='text' mimeClass='text'/>

    <AnalysisType name='all-tags'>
      <AnnotationType ref='tag' hasIndefiniteCardinality='true'/>
    </AnalysisType>

    <AnchorType name='text-point'>
      <SignalType ref='text' role='text'/>
      <ParameterType ref='char' role='char'/>
    </AnchorType>

    <RegionType name='text-extent'>
      <AnchorType ref='text-point' role='start'/>
      <AnchorType ref='text-point' role='end'/>
    </RegionType>

    <AnnotationType name='tag'>
      <RegionType ref='text-extent' role='text-extent'/>
      <ContentType ref='tag-content' role='content'/>
    </AnnotationType>

    <ContentType name='tag-content'>
      <ParameterType ref='string' role='type'/>
    </ContentType>

    <ParameterType name='char'/>    
    <ParameterType name='string'/>

    <CorpusType name='sample'>
      <SignalType ref='text' hasIndefiniteCardinality='true'/>
      <AnchorType ref='text-point' hasIndefiniteCardinality='true'/>
      <RegionType ref='text-extent' hasIndefiniteCardinality='true'/>
      <AnalysisType ref='all-tags' role='all-tags'/>
    </CorpusType>
  </TypeDefinitions>
</Scheme>
